name: MultiArch

on: [push, pull_request]

jobs:
  buildx_qemu:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        src:
          - debian
 #         - fedora
        arch:
          - x86_64
#          - i386
#          - aarch64
#          - arm
    name: 'Build: ${{ matrix.src }} · ${{ matrix.arch }}'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: matt2005/pi-cross-compile:latest
